services:
  - type: web
    name: expense-tracker
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.jdk
    plan: free